// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDijhjyjrqKu8cGgVKxX27ycvT8VwMJ0ZM',
    appId: '1:631299063556:web:c057968cd4f489e2ce9a51',
    messagingSenderId: '631299063556',
    projectId: 'project-management-ec37f',
    authDomain: 'project-management-ec37f.firebaseapp.com',
    storageBucket: 'project-management-ec37f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j9ADB_253Kv4xtdR3bUH8Jz-QUSm2pI',
    appId: '1:631299063556:android:e388149600f321f3ce9a51',
    messagingSenderId: '631299063556',
    projectId: 'project-management-ec37f',
    storageBucket: 'project-management-ec37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19LjbsfFUytNaX1GTWt-Xr8K9yxDe7pk',
    appId: '1:631299063556:ios:b661ef372974268dce9a51',
    messagingSenderId: '631299063556',
    projectId: 'project-management-ec37f',
    storageBucket: 'project-management-ec37f.appspot.com',
    iosBundleId: 'com.example.projectManagement',
  );
}
